name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build-loyalty:
    name: build loyalty
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build tests
        run: |
          docker build -t loyalty:latest -f ./loyalty.dockerfile . --target=build
          docker save loyalty:latest > loyalty_build.tar
      - name: build backend
        run: |
          docker build -t loaylty:latest -f ./loyalty.dockerfile . --target=release
          docker save loyalty:latest > loyalty_release.tar
      - uses: actions/upload-artifact@v4 
        with: 
          name: tests-loyalty-artefact 
          path: loyalty_build.tar
      - uses: actions/upload-artifact@v4 
        with: 
          name: backend-loyalty-artefact 
          path: loyalty_release.tar

  build-payment:
    name: build payment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build tests
        run: |
          docker build -t payment:latest -f ./payment.dockerfile . --target=build
          docker save payment:latest > payment_build.tar
      - name: build backend
        run: |
          docker build -t payment:latest -f ./payment.dockerfile . --target=release
          docker save payment:latest > payment_release.tar
      - uses: actions/upload-artifact@v4 
        with: 
          name: tests-payment-artefact 
          path: payment_build.tar
      - uses: actions/upload-artifact@v4 
        with: 
          name: backend-payment-artefact 
          path: payment_release.tar

  build-reservation:
    name: build reservation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build tests
        run: |
          docker build -t reservation:latest -f ./reservation.dockerfile . --target=build
          docker save reservation:latest > reservation_build.tar
      - name: build backend
        run: |
          docker build -t reservation:latest -f ./reservation.dockerfile . --target=release
          docker save reservation:latest > reservation_release.tar
      - uses: actions/upload-artifact@v4 
        with: 
          name: tests-reservation-artefact 
          path: reservation_build.tar
      - uses: actions/upload-artifact@v4 
        with: 
          name: backend-reservation-artefact 
          path: reservation_release.tar

  build-gateway:
    name: build gateway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build backend
        run: |
          docker build -t gateway:latest -f ./gateway.dockerfile . --target=release
          docker save gateway:latest > gateway_release.tar
      - uses: actions/upload-artifact@v4 
        with: 
          name: backend-gateway-artefact 
          path: gateway_release.tar

  test-loyalty:
    name: test loyalty
    runs-on: ubuntu-latest
    needs: build-loyalty
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with: 
          name: tests-loyalty-artefact 
      - name: run tests
        run: |
          docker load < loyalty_build.tar
          docker compose -f ./docker-compose.tests.yml up loyalty_tests
          if [[ 0 == $? ]]
          then
            echo "TESTS_STATUS=success" >> $GITHUB_ENV
          else
            echo "TESTS_STATUS=failed" >> $GITHUB_ENV
          fi

  test-payment:
    name: test payment
    runs-on: ubuntu-latest
    needs: build-payment
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with: 
          name: tests-payment-artefact 
      - name: run tests
        run: |
          docker load < payment_build.tar
          docker compose -f ./docker-compose.tests.yml up payment_tests
          if [[ 0 == $? ]]
          then
            echo "TESTS_STATUS=success" >> $GITHUB_ENV
          else
            echo "TESTS_STATUS=failed" >> $GITHUB_ENV
          fi

  test-reservation:
    name: test reservation
    runs-on: ubuntu-latest
    needs: build-reservation
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with: 
          name: tests-reservation-artefact 
      - name: run tests
        run: |
          docker load < reservation_build.tar
          docker compose -f ./docker-compose.tests.yml up reservation_tests
          if [[ 0 == $? ]]
          then
            echo "TESTS_STATUS=success" >> $GITHUB_ENV
          else
            echo "TESTS_STATUS=failed" >> $GITHUB_ENV
          fi

  run:
    name: run
    runs-on: ubuntu-latest
    needs: [test-loyalty, test-payment, test-reservation, build-gateway]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with: 
          name: backend-loyalty-artefact 
      - uses: actions/download-artifact@v4
        with: 
          name: backend-payment-artefact 
      - uses: actions/download-artifact@v4
        with: 
          name: backend-reservation-artefact 
      - uses: actions/download-artifact@v4
        with: 
          name: backend-gateway-artefact 
      - name: Run
        run: |
          docker load < loyalty_release.tar
          docker load < payment_release.tar
          docker load < reservation_release.tar
          docker compose -f ./docker-compose.yml up -d

  integration-tests:
    name: Autograding
    runs-on: ubuntu-latest
    needs: run
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2
      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v2/postman/collection.json
          environment: v2/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 2
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v
