name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build tests
        run: |
          docker build -t loyalty:latest -f ./loyalty.dockerfile . --target=build
          docker build -t payment:latest -f ./payment.dockerfile . --target=build
          docker build -t reservation:latest -f ./reservation.dockerfile . --target=build
          docker save loyalty:latest > loyalty_build.tar
          docker save payment:latest > payment_build.tar
          docker save reservation:latest > reservation_build.tar
          zip test.zip *_build.tar
          rm loyalty_build.tar payment_build.tar reservation_build.tar
      - name: build backend
        run: |
          docker build -t loaylty:latest -f ./loyalty.dockerfile . --target=release
          docker build -t payment:latest -f ./payment.dockerfile . --target=release
          docker build -t reservation:latest -f ./reservation.dockerfile . --target=release
          docker build -t gateway:latest -f ./gateway.dockerfile . --target=release
          docker save loyalty:latest > loyalty_release.tar
          docker save payment:latest > payment_release.tar
          docker save reservation:latest > reservation_release.tar
          docker save gateway:latest > gateway_release.tar
          zip release.zip *_release.tar
          rm loyalty_release.tar payment_release.tar reservation_release.tar gateway_release.tar
      - uses: actions/upload-artifact@v4 
        with: 
          name: tests-artefact 
          path: test.zip
      - uses: actions/upload-artifact@v4 
        with: 
          name: backend-artefact 
          path: release.zip

  test:
    name: test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with: 
          name: tests-artefact 
      - name: run tests
        run: |
          unzip test.zip
          docker load < loyalty_build.tar
          docker load < payment_build.tar
          docker load < reservation_build.tar
          docker compose -f ./docker-compose.tests.yml up --exit-code-from tests
          if [[ 0 == $? ]]
          then
            echo "TESTS_STATUS=success" >> $GITHUB_ENV
          else
            echo "TESTS_STATUS=failed" >> $GITHUB_ENV
          fi
  run:
    name: run
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with: 
          name: backend-artefact 
      - name: Run
        run: |
          unzip release.zip
          docker load < loyalty_release.tar
          docker load < payment_release.tar
          docker load < reservation_release.tar
          docker compose -f ./docker-compose.yml up

  integration-tests:
    name: Autograding
    runs-on: ubuntu-latest
    needs: run
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2
      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v2/postman/collection.json
          environment: v2/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 2
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v
